### ISSUE TITLE
Package Maintainer Request

### ISSUE THREAD

**Issue by zjuyk** [Schrodinger-Hat/ImageGoNord-pip#12]
I am willing to maintain this package in archlinux. Here is the [link](https://aur.archlinux.org/packages/python-image-go-nord/)

But I notice that you didn't setup a test for this package, so I skip it. Are you going to test your package by pytest or other tools?
Please let me know if you change the plan.

Thank you for such a gool tool! I am a nord user too.

**Comment by TheJoin95** [comment]
Hi there, thank you for let us know about this! We love Archlinux.
We did not publish any pytest result because we would like to improve the library and the unit test itself.

You can find a first try of unit test via pytest [here](https://github.com/Schrodinger-Hat/ImageGoNord-pip/blob/master/ImageGoNord/GoNord_test.py).

**Comment by zjuyk** [comment]
Get it, I'll stay focused on it.
