### ISSUE TITLE
Feature request: make the AI-related functionality and dependencies optional

### ISSUE THREAD

**Issue by JinEnMok** [Schrodinger-Hat/ImageGoNord-pip#26]
This is mostly related to the dependencies, and `torch` in particular - the current wheel for Linux is ~800MB, and that's even without its own dependencies. This is due to the included support for many CUDA platforms... which users may not even have? I'm running on an all-integrated Intel laptop, and I'm likely not the only one who can't/won't use GPU-accelerated stuff.

By comparison, the previous version is relatively tiny. 

So maybe it'd be possible to move the torch-y deps to optional, e.g. `image-go-nord[torch]`?

**Comment by JinEnMok** [comment]
Ah, my bad about the duplicate. I took a break to sip tea after I started writing it and didn't notice you'd added an issue already

**Comment by TheJoin95** [comment]
Yes, you're totally right.
I've opened #25 which is going to address this.
It's going to be an analysis issue which will generate some issues in order to make the best changes to the package and the ImageGoNord (I would say Image Go Wild) project.

Closing this as a duplicate, but really appreciated your feedback on this and if you'd like to contribute to this (with a review, by opening other issues, opening PR) please feel free to do it :)
